'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import { ArrowRight, BedDouble, Bath, Menu, X, MapPin, Ruler, Search, Globe2, BriefcaseBusiness } from 'lucide-react'
import { images, properties, type Property } from '@/lib/properties'

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-foreground/45 p-0 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label={title}>
    <div className="max-h-[90vh] w-full overflow-y-auto bg-background p-6 sm:max-w-lg sm:p-10"><div className="mb-8 flex items-start justify-between"><div><p className="eyebrow">Ashbourne & Rowe</p><h2 className="mt-2 font-serif text-3xl">{title}</h2></div><button onClick={onClose} aria-label="Close dialog" className="icon-button"><X size={20}/></button></div>{children}</div>
  </div>
}

function EnquiryForm({ viewing = false }: { viewing?: boolean }) {
  const [sent, setSent] = useState(false)
  if (sent) return <div className="border border-border bg-secondary p-8 text-center"><p className="eyebrow">Thank you</p><h3 className="mt-3 font-serif text-3xl">We&apos;ll be in touch.</h3><p className="mt-3 text-muted-foreground">A member of our team will contact you shortly.</p></div>
  return <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); setSent(true) }}><div className="grid gap-4 sm:grid-cols-2"><label>Full name<input required name="name" /></label><label>Email address<input required type="email" name="email" /></label></div><label>Phone number<input required type="tel" name="phone" /></label>{viewing && <label>Preferred date<input type="date" name="date" /></label>}<label>Message<textarea name="message" rows={4} placeholder={viewing ? 'Tell us anything helpful about your viewing.' : 'How can we help?'}/></label><button className="button button-dark w-full" type="submit">{viewing ? 'Request a Viewing' : 'Send Enquiry'} <ArrowRight size={16}/></button></form>
}

function Header({ onValuation }: { onValuation: () => void }) {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><Link href="/" className="wordmark" onClick={() => setOpen(false)}>ASHBOURNE <span>&</span> ROWE</Link><nav className="desktop-nav"><Link href="/#properties">Properties</Link><Link href="/#sell">Sell</Link><Link href="/#sell">Let</Link><Link href="/#neighbourhoods">Neighbourhoods</Link><Link href="/#about">About</Link><Link href="/#journal">Journal</Link></nav><button onClick={onValuation} className="button button-dark desktop-cta">Book a Valuation</button><button className="mobile-menu" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X/> : <Menu/>}</button>{open && <div className="mobile-nav"><Link href="/#properties" onClick={() => setOpen(false)}>Properties</Link><Link href="/#sell" onClick={() => setOpen(false)}>Sell & Let</Link><Link href="/#neighbourhoods" onClick={() => setOpen(false)}>Neighbourhoods</Link><Link href="/#about" onClick={() => setOpen(false)}>About</Link><Link href="/#journal" onClick={() => setOpen(false)}>Journal</Link><button onClick={onValuation} className="button button-dark">Book a Valuation</button></div>}</header>
}

function PropertyCard({ property }: { property: Property }) { return <Link href={`/properties/${property.slug}`} className="property-card"><div className="property-image"><Image src={property.image} alt={property.name} fill sizes="(max-width: 768px) 100vw, 33vw" unoptimized/><span>For Sale</span></div><div className="property-copy"><p className="eyebrow">{property.location}</p><h3 className="font-serif text-2xl">{property.name}</h3><p className="mt-2 text-lg">{property.price}</p><div className="property-meta"><span><BedDouble size={15}/> {property.beds} beds</span><span><Bath size={15}/> {property.baths} baths</span><span><Ruler size={15}/> {property.sqft} sq ft</span></div><span className="view-link">View property <ArrowRight size={15}/></span></div></Link> }

export function HomePage() {
  const [valuation, setValuation] = useState(false); const [query, setQuery] = useState(''); const [mode, setMode] = useState('Buy');
  const filtered = useMemo(() => properties.filter(p => !query || `${p.name} ${p.location}`.toLowerCase().includes(query.toLowerCase())), [query])
  return <div><Header onValuation={() => setValuation(true)}/><main><section className="hero"><Image src={images.townhouse} alt="Sunlit contemporary London residence" fill priority unoptimized sizes="100vw"/><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow text-white/75">London & the country</p><h1>Exceptional homes.<br/><em>Considered service.</em></h1><p className="hero-lede">Independent property specialists representing remarkable homes across London and the English countryside.</p><div className="hero-actions"><Link href="#properties" className="button button-light">Explore Properties <ArrowRight size={16}/></Link><button className="button button-outline-light" onClick={() => setValuation(true)}>Book a Valuation</button></div></div><div className="scroll-cue">Scroll to explore <span/></div></section>
  <section className="search-section"><div className="search-top"><p className="eyebrow">Find your next address</p><div className="toggle">{['Buy','Rent'].map(x => <button key={x} className={mode === x ? 'active' : ''} onClick={() => setMode(x)}>{x}</button>)}</div></div><div className="search-fields"><label><MapPin size={16}/> Location<input value={query} onChange={e => setQuery(e.target.value)} placeholder="London, countryside or postcode"/></label><label>Minimum price<select><option>Any price</option><option>£1,000,000</option><option>£2,000,000</option></select></label><label>Maximum price<select><option>Any price</option><option>£3,000,000</option><option>£5,000,000</option></select></label><label>Bedrooms<select><option>Any bedrooms</option><option>3+ bedrooms</option><option>5+ bedrooms</option></select></label><button className="button button-dark"><Search size={16}/> Search</button></div></section>
  <section id="properties" className="section"><div className="section-heading"><div><p className="eyebrow">The collection</p><h2>Selected Properties</h2></div><p>A curated collection of exceptional homes currently represented by Ashbourne & Rowe.</p></div><div className="property-grid">{filtered.map(p => <PropertyCard key={p.slug} property={p}/>)}</div>{!filtered.length && <p className="empty">No properties matched your search. Please try another location.</p>}</section>
  <section id="about" className="split-section"><div className="split-image"><Image src={images.hampstead} alt="Architectural interior with natural light" fill unoptimized sizes="50vw"/></div><div className="split-copy"><p className="eyebrow">Our approach</p><h2>Property, handled personally.</h2><p>We combine detailed local knowledge, discreet personal service and contemporary property marketing to make every move feel considered.</p><p>From the first conversation to the final signature, our work is defined by care, clarity and an instinct for what makes a home exceptional.</p><Link href="#contact" className="text-link">Discover our story <ArrowRight size={16}/></Link></div></section>
  <section id="sell" className="dark-section"><div><p className="eyebrow text-stone">A considered move</p><h2>Considering a move?</h2><p>Whether you are preparing to sell now or simply curious about the value of your home, our team offers considered, confidential advice.</p><button onClick={() => setValuation(true)} className="button button-light">Book a Complimentary Valuation <ArrowRight size={16}/></button></div><div className="dark-image"><Image src={images.estate} alt="Country estate viewed through trees" fill unoptimized sizes="45vw"/></div></section>
  <section id="neighbourhoods" className="section places"><div className="section-heading"><div><p className="eyebrow">Local knowledge</p><h2>Places We Know</h2></div><p>Distinctive places, understood in detail.</p></div><div className="places-grid">{[['Mayfair',images.apartment,'Quiet grandeur at the heart of London.'],['Notting Hill',images.townhouse,'Colour, character and a village rhythm.'],['Hampstead',images.hampstead,'Leafy lanes and a creative spirit.'],['Richmond',images.riverside,'The river, the park and room to breathe.'],['Chelsea',images.cotswolds,'Garden squares and considered living.'],['The Cotswolds',images.estate,'A slower pace, beautifully lived.']].map(([name,img,desc]) => <article className="place" key={name}><div><Image src={img} alt={`${name} neighbourhood`} fill unoptimized sizes="(max-width: 768px) 100vw, 33vw"/></div><p className="eyebrow">{name}</p><p>{desc}</p></article>)}</div></section>
  <section className="stats-section"><div><strong>£420M+</strong><span>Property represented</span></div><div><strong>18</strong><span>Years combined experience</span></div><div><strong>96%</strong><span>Asking price achieved</span></div><div><strong>London + Country</strong><span>Coverage</span></div></section>
  <section className="quote-section"><p className="quote-mark">“</p><blockquote>Ashbourne & Rowe understood immediately that selling our home required more than simply putting it on the market. Their attention to detail, communication and discretion were exceptional.</blockquote><p className="eyebrow">Private Client, Hampstead</p></section>
  <section id="journal" className="section journal"><div className="section-heading"><div><p className="eyebrow">The journal</p><h2>Notes on living well</h2></div><Link href="#journal" className="text-link">View all stories <ArrowRight size={16}/></Link></div><div className="journal-grid">{[['Inside London’s Most Desirable Neighbourhoods',images.apartment],['How to Prepare an Exceptional Home for Market',images.hampstead],['Why Country Living Is Attracting a New Generation of Buyers',images.cotswolds]].map(([title,img]) => <article key={title}><div><Image src={img} alt={title} fill unoptimized sizes="33vw"/></div><p className="eyebrow">Insights · 6 min read</p><h3 className="font-serif text-2xl">{title}</h3><span className="view-link">Read story <ArrowRight size={15}/></span></article>)}</div></section>
  <section id="contact" className="contact-section"><p className="eyebrow">Start a conversation</p><h2>Thinking of moving?</h2><p>Whether buying, selling or simply exploring your options, we would be delighted to hear from you.</p><div><button onClick={() => setValuation(true)} className="button button-dark">Book a Valuation <ArrowRight size={16}/></button><a href="tel:+442079460280" className="button button-outline-dark">Speak to an Advisor</a></div></section></main><Footer/>{valuation && <Modal title="Book a valuation" onClose={() => setValuation(false)}><EnquiryForm/></Modal>}</div>
}

function Footer() { return <footer><div><Link href="/" className="wordmark">ASHBOURNE <span>&</span> ROWE</Link><p>London & Country<br/>Property Specialists</p></div><div><p className="eyebrow">Explore</p><Link href="#properties">Properties</Link><Link href="#sell">Sell & Let</Link><Link href="#neighbourhoods">Neighbourhoods</Link><Link href="#journal">Journal</Link></div><div><p className="eyebrow">Visit us</p><p>21 Grosvenor Street<br/>Mayfair<br/>London W1K 4QJ</p><p>+44 (0)20 7946 0280<br/>hello@ashbourneandrowe.co.uk</p></div><div><p className="eyebrow">Follow</p><p className="social"><Globe2 size={18}/> Instagram</p><p className="social"><BriefcaseBusiness size={18}/> LinkedIn</p></div><small>Concept website created as a portfolio project. Ashbourne & Rowe is a fictional brand.</small></footer> }

export function PropertyPage({ property }: { property: Property }) { const [view, setView] = useState(false); return <div><Header onValuation={() => setView(true)}/><main className="detail"><div className="detail-hero"><Image src={property.image} alt={property.name} fill priority unoptimized sizes="100vw"/><div className="hero-overlay"/><div><p className="eyebrow text-white/75">{property.location}</p><h1>{property.name}</h1><p className="detail-price">{property.price}</p></div></div><div className="detail-body"><div className="detail-main"><p className="eyebrow">The property</p><h2>A home with its own point of view.</h2><p>{property.description}</p><div className="detail-facts"><span><BedDouble/> {property.beds} bedrooms</span><span><Bath/> {property.baths} bathrooms</span><span><Ruler/> {property.sqft} sq ft</span></div><h3>Key features</h3><ul>{property.features.map(f => <li key={f}>{f}</li>)}</ul><div className="floorplan"><span>Floor plan</span><p>Detailed plans available on request</p></div></div><aside><p className="eyebrow">Arrange a private viewing</p><h3 className="font-serif text-3xl">See it for yourself.</h3><p>Our team would be delighted to arrange a convenient time for you to visit.</p><button onClick={() => setView(true)} className="button button-dark w-full">Arrange a Viewing <ArrowRight size={16}/></button></aside></div><section className="detail-gallery"><Image src={images.apartment} alt="Interior detail" width={1200} height={800} unoptimized/><Image src={images.hampstead} alt="Light-filled living space" width={900} height={1100} unoptimized/></section></main><Footer/>{view && <Modal title="Arrange a viewing" onClose={() => setView(false)}><EnquiryForm viewing/></Modal>}</div> }
